### ISSUE TITLE
Random Teleport Locks Game Up

### ISSUE THREAD

**Issue by Darkosto** [ChiKitsune/SwapThings#1]
Hey ChiKitsune!

On MC version 1.18.2, it looks like the random teleport command is locking the game up. I'm not getting any logs or crashes to share. Any chance this is something you'd be able to look into?

MC: 1.18.2
Forge: 40.0.49
SwapThings: 1.0.0

**Comment by ChiKitsune** [comment]
Yea I can look into it.
I do have one question because I know of one issue with that command that I need to fix but I know I have it limited to the pre 1.18 Y level limits 0 - 255.
Need to publish my changes to make that configurable and to default to the new limits.

Do you think this might have to do with with is locking up your game?
Should really only lock it up with no message when it continues to try to find a place to teleport to but is unable to.
I'll double check my logic since should only try 20 x/z attempts but does check all y levels within that range and might be having issues with the new y levels or if is a dimension that doesn't have y levels in that limit.

Hopefully should have a less strict y level fix uploaded sometime tomorrow/Sunday.
Sorry about that

**Comment by ChiKitsune** [comment]
I've updated it and should hopefully fix the issue if it was the Y level.
Even if that wasn't your issue I added more checks so it shouldn't ever get stuck in a loop trying to find a teleport destination and lock up the game.

**Comment by Darkosto** [comment]
Looks like that was the needed fix! Everything is functional for me now. Thank you very much for looking into this! <3
