### ISSUE TITLE
Random Enchantment Not So Random

### ISSUE THREAD

**Issue by Darkosto** [ChiKitsune/SwapThings#2]
Hey!

I've setup my CCI to do a random enchantment for the items in my inventory. I have the setting on "POSSITIVE" but, 95% of the time items are give "Block Reach" despite having many more enchantments. Is there a way to allow much larger variety of enchantments? I didn't choose the "Random" option because I wasn't looking to have enchantments removed as that can happen with that command setting.

Thank you!
Darkosto

MC: 1.18.2
Swap Things: 1.0.1
Forge: 40.1.52

**Comment by ChiKitsune** [comment]
Hmm I'll check more into it.
It should be getting a new random number every time it is ran and the next random number based on everything in the Forge Enchantment Registry.
Taking a glance I could also improve the POSSITIVE so that if the random enchantment it chooses is already at max level that it chooses a different enchantment that isn't already maxed on it.
Which might help that at least after it already does that.
Do know there used to be a similar kind of issue where the random teleport didn't seem truly random until I changed things around but that fix is already in the RandomEnchanting command.
I'll try some idea I have.

Also, it wasn't until now that I noticed that POSSITIVE was spelled wrong... Want me to update that to POSITIVE too?

**Comment by Darkosto** [comment]
Hey!

if you're up to fixing up the spelling, I would not be opposed. I can make that adjustment in CCI easily.

If you need help testing out the fix, let me know and I could lend a hand.

Thank you!

**Comment by ChiKitsune** [comment]
I just uploaded to curseforge a 1.18.2 - 1.02 version with some changes listed below that should hopefully fix your issues and also allow more customization.
Part of the issue may have been I was forcing it to choose only enchantments that had a true value for "canEnchant" which may have had issues with certain items (like sticks) not have many valid enchantments. With the new config option can make it add any enchantment on any item (excluding any in the EXCLUDE config list)


Updated RandomEnchanting command with a few improvements
- Fixed the POSSITIVE argument to be spelled correctly as POSITIVE
- Added checks when using POSITIVE so that if the random enchantment is already on it at max level it will choose another random enchantment
- Added checks when using NEGATIVE that will always choose an enchantment that is already on it
- Added config option RandomEnchantingExclude to be able to exclude certain enchantment(s) from being randomly chosen
- Added config option randomEnchantForce to include possible enchantments that normally should go on the item if the value is TRUE. (i.e. protection enchantment on a sword)
- Added new message if a valid enchantment isn't found and increased the amount of times it can choose a random enchantment to 20 * all possible enchantment count. Was 50 times
